### PR TITLE
Upgrade to Django 1.11 and working filter list landing page

### PR DESCRIPTION
**Pull request by BjornvdLaan**
An upgrade has been performed to Django 1.11. This version is supported until mid 2020.

Also, the landing page that displays all policies is now working again and uses django-filters to filter based on the state. Styling is basic, but functional.

### CODE REVIEW

**Comment by frequent** [comment]
Cool! Let me check how I can merge this without too many conflicts :)

**Comment by BjornvdLaan** [comment]
There are no conflicts. Or do you have some  stuff locally?

**Comment by frequent** [comment]
yes, quite a bit. let me compare quickly.

**Comment by BjornvdLaan** [comment]
If you push it, I can help you!

**Comment by frequent** [comment]
Ok. I think it's mostly views.py which indentation. The rest should be easy. Pushing in a second.

**Comment by BjornvdLaan** [comment]
Ah maybe we should sync indent settings for pycharm

**Comment by frequent** [comment]
I'm not using pycharm, but the only thing I'm currently enforcing "by hand" is 2 space indentation :) I'm happy to use something in common, so let me know what settings you have and I'll follow suite.

**Comment by frequent** [comment]
here we go :)

**Comment by frequent** [comment]
Thanks so much! Let's see if I can get it to run on my local machine :)

**Comment by BjornvdLaan** [comment]
This does not contain the tags yet, but clears the way for it.

Don't forget to migrate and pip install.

**Pull request merged**
